# Generated by Django 6.0.3 on 2026-07-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_assigned', 'Tarea asignada'), ('task_completed', 'Tarea completada'), ('comment_added', 'Nuevo comentario'), ('member_added', 'Agregado al proyecto')], max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'notificación',
                'ordering': ['-created_at'],
            },
        ),
    ]
