# Generated by Django 6.0.3 on 2026-07-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_assigned', 'Tarea asignada'), ('task_completed', 'Tarea completada'), ('comment_added', 'Nuevo comentario'), ('member_added', 'Agregado al proyecto'), ('member_removed', 'Removido del proyecto')], max_length=30),
        ),
    ]
